spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Chaeum
    username: chaeum
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update